name: Stagehand

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java: [ '8', '11', '17' ]
        playwright: ['1.17.0', '1.18.0']
    runs-on: ${{ matrix.os }}
    name: ${{matrix.os}} - Java ${{ matrix.java }} - Playwright ${{matrix.playwright}}
    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - run: mvn test "-Dplaywright.version=${{matrix.playwright}}" --file pom.xml
